CREATE DATABASE IF NOT EXISTS APInotes ;

CREATE TABLE IF NOT EXISTS APInotes.notes ( 
	title VARCHAR(30) NOT NULL , 
	content TEXT NOT NULL, 
    made_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


